name: taskuapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: ^0.15.2
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/logo.png

  fonts:
     - family: Roxborough
       fonts:
         - asset: assets/fonts/roxborough-cf-light.ttf
           style: normal
           weight: 400
         - asset: assets/fonts/roxborough-cf-regular.ttf
           style: normal
           weight: 600
         - asset: assets/fonts/roxborough-cf-bold.ttf
           style: normal
           weight: 700

     - family: Telegraf
       fonts:
         - asset: assets/fonts/telegraf-light.otf
           style: normal
           weight: 400
         - asset: assets/fonts/telegraf-regular.otf
           style: normal
           weight: 600
         - asset: assets/fonts/telegraf-bold.otf
           style: normal
           weight: 700

flutter_native_splash:
  color: "#F5F2ED"
  color_dark: "#121210"
  image: assets/logo.png
  image_dark: assets/logo.png
  android: true
  ios: false

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
